# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 02d97421513e0c7414f593103f035d968c5ec1694f651cccae4aac0f3404f12c66b5becefd853c5cf6e81fa1c0185f1a711f09bb4bdac8c4f896b34fd2b43937

test:
  secret_key_base: 4838ea5aa2ef8a37c63d01f19ec6779bad40803d19d7baef3092adc3fd0bf19fc9fed6adad296aa417cf59a84b7d78c3a19ad442044104cf0519bb3f5c56b320

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
